name: CD

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: huangtingluo
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}
        repository: huangtingluo/binary-json-formatter
        tags: release
